# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9" 
  config.vm.hostname = "almalinux9-lab"

  config.vm.provision "shell", path: "provision/setup.sh"

  config.vm.network "private_network", ip: "192.168.10.100"

  config.vm.provider "vmware_desktop" do |v|
    v.cpus = 2
    v.memory = 2048
    
    # ЭТУ СТРОКУ НУЖНО УДАЛИТЬ:
    # v.name = "almalinux9-single-node" 
    
    v.allowlist_verified = true 
  end
end